name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build the app
        run: ./gradlew build

      - name: Static Analysis
        run: ./gradlew ktlintCheck